import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createApp, hashPassword } from '../server/app.mjs';
import { ageOn, passwordError, registrationErrors } from '../shared/validation.mjs';
import { commonPasswords } from '../shared/common-passwords.mjs';

test('Form rules and age boundaries', () => {
  const today = new Date(2026, 8, 19, 12);
  assert.equal(ageOn('2010-09-19', today), 16);
  assert.equal(ageOn('2010-09-20', today), 15);
  assert.equal(ageOn('2010-02-30', today), -1);
  assert.equal(ageOn('2027-01-01', today), -1);
  assert.ok(passwordError('abcdefgh'));
  assert.ok(passwordError('Abcdefg1'));
  assert.ok(passwordError('Ab1!'));
  assert.ok(passwordError('Aa1!' + 'a'.repeat(17)));
  assert.equal(passwordError('Learnico9!Study'), '');
  for (const password of commonPasswords) assert.ok(passwordError(password));
  assert.ok(registrationErrors({}).phone);
});

test('Registration, authorization, orders, reviews and admin CRUD', async t => {
  const seed = JSON.parse(readFileSync(new URL('../server/seed.json', import.meta.url)));
  seed.users = [{ id: 'admin', email: 'admin@learnico.local', nickname: 'Admin', role: 'admin', passwordHash: hashPassword('Admin9!Study') }];
  seed.cart = []; seed.favorites = []; seed.orders = []; seed.feedback = [];
  const { app, db } = createApp(seed);
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = 'http://127.0.0.1:' + server.address().port;
  async function api(path, method = 'GET', body, token, expected = 200) {
    const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
    const value = await response.json();
    assert.equal(response.status, expected, method + ' ' + path + ': ' + JSON.stringify(value));
    return value;
  }
  const person = { firstName: 'Test', lastName: 'Learner', middleName: '', email: 'learner@example.test', phone: '+375 29 123-45-67', birthDate: '2000-01-01', passwordMode: 'manual', password: 'Learnico9!Study', confirmPassword: 'Learnico9!Study', nickname: 'TestLearner', acceptedTerms: true };
  await api('/users', 'POST', { ...person, phone: '+79991234567' }, null, 422);
  await api('/users', 'POST', { ...person, birthDate: '2020-01-01' }, null, 422);
  await api('/users', 'POST', { ...person, confirmPassword: 'wrong' }, null, 422);
  await api('/users', 'POST', { ...person, acceptedTerms: false }, null, 422);
  const customer = await api('/users', 'POST', { ...person, role: 'admin' }, null, 201);
  assert.equal(customer.user.role, 'customer');
  assert.ok(!JSON.stringify(customer).includes('password'));
  const stored = db.get('users').find({ id: customer.user.id }).value();
  assert.ok(stored.passwordHash && !stored.passwordHash.includes(person.password));
  assert.equal(stored.password, undefined);
  await api('/users', 'POST', person, null, 422);
  assert.equal((await api('/availability?nickname=testlearner')).available, false);
  const second = await api('/users', 'POST', { ...person, nickname: 'AnotherLearner', email: 'another@example.test', phone: '+375441234567' }, null, 201);
  await api('/users/me', 'PUT', person, null, 401);
  await api('/users/me', 'PUT', { ...person, firstName: '' }, customer.token, 422);
  await api('/users/me', 'PUT', { ...person, email: second.user.email }, customer.token, 422);
  const profile = await api('/users/me', 'PUT', { ...person, firstName: 'Updated', email: 'updated@example.test' }, customer.token);
  assert.equal(profile.firstName, 'Updated');
  assert.equal((await api('/auth/me', 'GET', undefined, customer.token)).email, 'updated@example.test');
  assert.equal(db.get('users').find({ id: customer.user.id }).value().firstName, 'Updated');
  const admin = await api('/auth/login', 'POST', { email: 'admin@learnico.local', password: 'Admin9!Study' });
  await api('/auth/login', 'POST', { email: person.email, password: 'incorrect' }, null, 401);
  await api('/users', 'GET', undefined, customer.token, 403);
  assert.ok(!(await api('/users', 'GET', undefined, admin.token)).some(user => user.passwordHash));
  await api('/db', 'GET', undefined, null, 404);
  await api('/server/seed.json', 'GET', undefined, null, 404);
  await api('/courses', 'POST', {}, customer.token, 403);
  await api('/courses', 'POST', {}, admin.token, 422);
  const course = { title: 'Testing course', description: 'A practical testing course.', category: 'Testing', price: 12.25, rating: 4.5, duration: 8, level: 'Beginner', image: 'images/course-1.png' };
  const added = await api('/courses', 'POST', course, admin.token, 201);
  const updated = await api('/courses/' + added.id, 'PUT', { ...course, price: 15.25 }, admin.token);
  assert.equal(updated.price, 15.25);
  const filtered = await api('/courses?category=Testing&price_gte=15&_page=1&_limit=6&_sort=price&_order=desc');
  assert.equal(filtered[0].id, added.id);
  await api('/cart', 'POST', { courseId: added.id }, null, 401);
  const cart = await api('/cart', 'POST', { courseId: added.id, userId: second.user.id }, customer.token, 201);
  assert.equal(cart.userId, customer.user.id);
  await api('/cart/' + cart.id, 'PATCH', { quantity: 0 }, customer.token, 422);
  await api('/cart/' + cart.id, 'PATCH', { quantity: 2 }, second.token, 404);
  await api('/cart/' + cart.id, 'PATCH', { quantity: 2 }, customer.token);
  assert.deepEqual(await api('/cart', 'GET', undefined, second.token), []);
  await api('/feedback', 'POST', { courseId: added.id, text: 'This is a useful course for beginners.' }, customer.token, 422);
  await api('/orders', 'POST', {}, second.token, 422);
  const order = await api('/orders', 'POST', { totalCents: 1, userId: second.user.id }, customer.token, 201);
  assert.equal(order.totalCents, 3050);
  assert.equal(order.userId, customer.user.id);
  assert.deepEqual(await api('/cart', 'GET', undefined, customer.token), []);
  await api('/orders', 'POST', {}, customer.token, 422);
  await api('/feedback', 'POST', { courseId: added.id, text: 'too short' }, customer.token, 422);
  await api('/feedback', 'POST', { courseId: added.id, text: 'This is a useful course for beginners.' }, admin.token, 403);
  const review = await api('/feedback', 'POST', { courseId: added.id, text: 'This is a useful course for beginners.', userId: second.user.id }, customer.token, 201);
  assert.equal(review.userId, customer.user.id);
  assert.equal((await api('/feedback?courseId=' + added.id + '&userId=' + customer.user.id, 'GET', undefined, admin.token)).length, 1);
  assert.equal((await api('/feedback?userId=' + second.user.id, 'GET', undefined, admin.token)).length, 0);
  await api('/feedback/' + review.id, 'DELETE', undefined, customer.token, 403);
  await api('/feedback/' + review.id, 'DELETE', undefined, admin.token);
  await api('/courses/' + added.id, 'DELETE', undefined, admin.token);
  assert.equal((await api('/orders', 'GET', undefined, customer.token))[0].items[0].price, 15.25);
  assert.deepEqual(await api('/purchased-courses', 'GET', undefined, customer.token), []);
  await api('/auth/logout', 'POST', {}, customer.token);
  await api('/auth/me', 'GET', undefined, customer.token, 401);
});
